@startuml Class_Diagram_UML
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 18
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2
skinparam ArrowColor #red
hide empty members


' package Model
' {
    class Player
    {
        - {static} players : int
        - money : double
        - loans : double
        - bills : double
        - position : int
        - id : int
        - roll : int
        - task : String
        - hasPlayed : boolean
        - isTaskDone : boolean
        - pawnImageName : String

        'aggregation of DealCard
        'aggregation of MailCard
        +Player()

        +GetPawnImageName() : String
        +GetId() : String
        +GetRoll() : int
        +HasPlayed() : boolean
        +IsTaskDone() : boolean
        +GetTask() : String
        +GetMoney() : double
        +GetLoans() : double
        +GetBills() : double
        +GetPosition() : int

        +SetPawnImageName(imageName : String) : void
        +SetId(id : int) : void
        +SetRoll(roll : int) : void
        +SetHasPlayed(hasPlayed : boolean) : void
        +SetTaskDone(isDone : boolean) : void
        +SetTask(task : String) : void 
        +SetMoney(money : double) : void
        +SetLoans(loans : double) : void
        +SetBills(bills : double) : void
        +SetPosition(position : int) : void

        +RollDice() : void
        +AddDealCard(card : DealCard) : void  
        +GetMailCards() : LinkedList<MailCard> 
        +AddDealCard(card : MailCard) : void  
        +GetDealCards() : LinkedList<DealCard>   
    }
    Player "1" --o "*" DealCard
    Player "1" --o "*" MailCard

    class Tile
    {
        'association from CardPosition
    }
    Tile "1" -- "1" CardPosition


    abstract class CardPosition
    {
        -icon : String

        -position : int
        -day : String

        'dependency with Controller
        CardPosition(imageName : String, controller : Controller)

        +GetPosition() : int
        +GetDay() : String
        +GetIcon() : String
        +GetController() : Controller

        +SetPosition(position : int) : void
        +SetDay(day : int) : void
        +SetIcon(icon : String) : void
        +SetController(controller : Controller) : void

        +{abstract}performAction() : void
    }
    CardPosition --* Controller.Controller


    abstract class MailPosition extends CardPosition
    {    
        MailPosition(imageName : String, controller : Controller)
    }
    MailPosition --* Controller.Controller

    class OneMailPosition extends MailPosition
    {
        +OneMailPosition(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    OneMailPosition --* Controller.Controller

    class TwoMailPosition extends MailPosition
    {
        +TwoMailPosition(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
        -ShowCard(card : MailCard, player : Player) : void
    }
    TwoMailPosition --* Controller.Controller


    class DealPosition extends CardPosition
    {
        +DealPosition(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    DealPosition --* Controller.Controller

    class Sweeptakes extends CardPosition
    {
        +SweepTakes(imageName : String)
        +performAction(player : Player) : void
        +toString() : String
    }
    

    class Lottery extends CardPosition
    {
        +Lottery(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    Lottery --* Controller.Controller

    class RadioContest extends CardPosition
    {
        +RadioContest(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    RadioContest --* Controller.Controller

    class BuyerPosition extends CardPosition
    {
        +BuyerPosition(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    BuyerPosition --* Controller.Controller

    class CasinoNight extends CardPosition
    {
        +CasinoNight(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    CasinoNight --* Controller.Controller

    class YardSale extends CardPosition
    {
        +YardSale(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    YardSale --* Controller.Controller

    class PayDayPosition extends CardPosition
    {
        +PayDayPosition(imageName : String, controller : Controller)
        +performAction(player : Player) : void
        +toString() : String
    }
    PayDayPosition --* Controller.Controller

    class StartPosition extends CardPosition
    {
        +StartPosition(imageName : String)
        +performAction(player : Player) : void
        +toString() : String
    }

    class JackpotPosition extends CardPosition
    {
        -jackpot : float

        +JackpotPosition(imageName : String)
        +performAction(player : Player) : void
        +GetJackpot() : float
        +SetJackpot(jackpot : float) : void
    }
    

    abstract class Card
    {
        -imageIcon : String
        -message : String
        -type : String

        Cards.Card(type,message,icon : String)
        +GetType() : String
        +GetImage() : String
        +GetMessage() : String
        +{abstract} Action(board:Board, player:Player) : void
    }
    Card --* Board

    class DealCard extends Card
    {
        -cost : double
        -value : double
        -choise1 : String
        -choise2 : String

        +DealCard(type,message:String, cost,value : float, icon,choise1,choise2:String)
        +GetChoise(choise : int) : String
        +GetCost() : float
        +GetValue() : float
        +Action(board:Board, player:Player) : void
    }

    abstract class MailCard extends Card
    {
        choise : String
        euro : float

        MailCard(type,message,choise:String, euro:float, icon : String)
        +GetEuro() : float
        +GetChoise() : String
    }

    class PayTheNeighborCard extends MailCard
    {
        +PayTheNeighborCard(type,message,choise:String, euro:float, icon : String)    
        +Action(board:Board, player:Player) : void

    }

    class MadMoneyCard extends MailCard
    {
        +MadMoneyCard(type,message,choise:String, euro:float, icon : String)
        +Action(board:Board, player:Player) : void            
    }

    class CharityCard extends MailCard
    {
        +CharityCard(type,message,choise:String, euro:float, icon : String)
        +Action(board:Board, player:Player) : void            
    }

    class BillCard extends MailCard
    {
        +BillCard(type,message,choise:String, euro:float, icon : String)
        +Action(board:Board, player:Player) : void            
    }

    class MoveToDealBuyerCard extends MailCard
    {
        +MoveToDealBuyerCard(type,message,choise:String, euro:float, icon : String)
        +Action(board:Board, player:Player) : void            
    }

    class AdvertisementCard extends MailCard
    {
        +AdvertisementCard(type,message,choise:String, euro:float, icon : String)
        +Action(board:Board, player:Player) : void            
    }


    class Board
    {
        -{static} MAX_TILES  : final int
        -{static} PLAYERS    : final int

        +Board()
        'aggregation of Player
        'aggregation of DealCard
        'aggregation of MailCard
        'aggregation of Tile
        'association with Tile
    }
    Board "1" --o "*" MailCard
    Board "1" --o "*" DealCard
    Board "1" --o "2"  Player
    Board "1" --o "31" Tile
    Board "1" -- "2" Tile
' }


' package View
' {
    class GraphicUI
    {
        -eastPanel : JPanel
        'association with BoardPanel
        'association with Controller 
        'association with InfoBoxPanel
        'aggregation from PlayerPane
        'aggregation from TilePanel
        +UpdateUI(): void
    }
    GraphicUI "1" -- "1" Controller
    GraphicUI "1" --o "2" PlayerPanel : consists of
    GraphicUI "1" -- "1" InfoBoxPanel: consists of
    GraphicUI "1" -- "1" BoardPanel : consists of

    class BoardPanel
    {
        +pawns : JLabel[]
        'aggregation from TilePanel
        'association with TilePanel
        'dependency from Controller
        +BoardPanel(controller : Controller)
        +UpdateJackpot(jackpot:double) : void
    }
    BoardPanel "1" -- "1" TilePanel : consists of
    BoardPanel "1" --o "31" TilePanel : consists of
    BoardPanel "1" --* Controller


    class PlayerPanel
    {
        'dependency from OptionDialog
        -playerText: JLabel
        +moneyText : JLabel
        +loanText  : JLabel
        +billsText : JLabel
        
        rollDieButton : JButton
        myDealCardsButton : JButton
        getLoanButton : JButton
        endTurnButton : JButton
        
        -imageURL : URL
        -diceImage : JLabel

        'association with player
        'association with controller
        +UpdatePlayerUI(money,loans,bills : double) : void

        +PlayerPanel(player : Player, controller : Controller)
        -SetController(controller: Controller) : void
        +GetController() : Controller

        -SetPlayer(player : Player) : void
        +GetPlayer() : Player

    }
    PlayerPanel --> Player
    PlayerPanel --> Controller
    PlayerPanel --* OptionDialog

    class TilePanel
    {
        text : JLabel
        image : JLabel

        'dependency from Tile
        TilePanel(tile : Tile)
    }
    TilePanel --* Tile

    class InfoBoxPanel
    {
        -duration : JLabel
        -turn : JLabel

        deal : JButton
        mail : JButton

        +UpdateInfoUI(duration,turn:int ,task:String) : void
        +GetTurnLabel() : JLabel
        'dependency from Controller
        InfoBoxPanel(controller: Controller)
        'dependency from OptionDialog
    }
    InfoBoxPanel ..* OptionDialog
    InfoBoxPanel ..* Controller

    class OptionDialog
    {
        -option : int
        +OptionDialog(title,text,op1,op2 : String, imageName : String)
        +GetOption() : int
    }
' }


' package Controller
' {
    class Controller
    {
        -turn : int
        -duration : int
        -endReached : int[]

        +GetTurn() : int
        +GetNextTurn() : int
        +SetNextTurn() : void
        +GetTask() : String
        +SetTask(task : String) : void
        +GetGameDuration()  : int
        +SetGameDuration() : void
        +GetPlayerEndReached() :  int[]
        +GetWinner() : String
        +GetBoard() : Board
        +GetUI() : GraphicUI
        +toString() : String
 
        +IsGameOver() : boolean
        +HasFinished(playerturn: int) : boolean
        +Shuffle(cards : List<?>)  : void
        +MovePlayer(player:Player, newPosition:int) : void

        'association from Board
        'dependency from GraphicUI
        -Init_Player(player : Player)   : void
        -Init_Tiles(num : int, pos : Position) : void
        -Init_Turn()   : void
        -Init_Duration()  : int
        -Init_MailCards() : void
        -Init_DealCards() : void
        -ReadFile(filename:String) : String[][]

    }

'}
    Controller "1" --* "1" GraphicUI
    Controller "1" --> "1" Board
    Controller "1" --> "1" Player
@enduml

@enduml
