@startuml Class_Diagram_UML
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
skinparam ArrowColor #red
hide empty members

package Controller
{
    class Controller
    {
        -turn : int
        -duration : int
        -endReached : int[]

        +GetTurn() : int
        +GetNextTurn() : int
        +SetNextTurn() : void
        +GetTask() : String
        +SetTask(task : String) : void
        +GetGameDuration()  : int
        +SetGameDuration() : void
        +GetPlayerEndReached() :  int[]
        +GetWinner() : String
        +GetBoard() : Board
        +GetUI() : GraphicUI
        +toString() : String
 
        +IsGameOver() : boolean
        +HasFinished(playerturn: int) : boolean
        +Shuffle(cards : List<?>)  : void
        +MovePlayer(player:Player, newPosition:int) : void

        'association from Board
        'dependency from GraphicUI
        -Init_Player(player : Player)   : void
        -Init_Tiles(num : int, pos : Position) : void
        -Init_Turn()   : void
        -Init_Duration()  : int
        -Init_MailCards() : void
        -Init_DealCards() : void
        -ReadFile(filename:String) : String[][]

    }

}
    Controller "1" --* "1" GraphicUI
    Controller "1" --> "1" Board
    Controller "1" --> "1" Player



@enduml